### ISSUE TITLE
build error (missing libepoxy dependency)

### ISSUE THREAD

**Issue by qumaciel** [bartoszek/AUR-blender-git#12]
It seams that libepoxy is missing from the dependencies.

At build time, the chaotic-aur chroot outputs:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Epoxy (missing: Epoxy_LIBRARY Epoxy_INCLUDE_DIR)
```

Cf. full log in [blender-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/blender-git.log)

**Comment by Technetium1** [comment]
It stopped showing that error once we included `cuda` as a dependency in https://github.com/chaotic-aur/interfere/commit/9f068368bbb2f67895e3cfa26be788e34c72d9f5
