### ISSUE TITLE
Missing libdecor as dep

### ISSUE THREAD

**Issue by sausix** [bartoszek/AUR-blender-git#14]
Sorry, github threw error 500 on submiting so my original compile output with the error vanished.

Blender now seems to require: `extra/libdecor` (Client-side decorations library for Wayland clients)

You can also bump Blender version to 3.4.0 Alpha.

Thanks.

**Comment by jtheoof** [comment]
This is correct. See the announcement here: https://code.blender.org/2022/10/wayland-support-on-linux/

**Comment by jtheoof** [comment]
I'm probably going to remove my package: https://aur.archlinux.org/packages/blender-wayland-git from the AUR after that. `blender-git` will build with WAYLAND flags ON by default. Which is great !

**Comment by bartoszek** [comment]
@jtheoof Sorry for the delay, I'm having problem building with `wayland` enabled, perhaps you can lend me a hand 😏 
```
-- Checking for module 'wayland-client>=1.12'
--   Found wayland-client, version 1.21.0
-- Checking for module 'wayland-egl'
--   Found wayland-egl, version 18.1.0
-- Checking for module 'wayland-scanner'
--   Found wayland-scanner, version 1.21.0
-- Checking for module 'wayland-cursor'
--   Found wayland-cursor, version 1.21.0
-- Checking for module 'wayland-protocols>=1.15'
--   Package 'wayland-protocols', required by 'virtual:world', not found
CMake Error at build_files/cmake/macros.cmake:1243 (if):
  if given arguments:
    "NOT" "AND" "ON"
  Unknown arguments specified
Call Stack (most recent call first):
  build_files/cmake/platform/platform_unix.cmake:672 (set_and_warn_library_found)
  CMakeLists.txt:1067 (include)
-- Configuring incomplete, errors occurred!
```

**Comment by jtheoof** [comment]
The fix is good. Thanks @bartoszek
