### ISSUE TITLE
uh

### ISSUE THREAD

**Issue by ctrlcctrlv** [bartoszek/AUR-blender-git#18]
i'm sorry, i pushed without looking at the AUR comments as the package was super broken. i have the maintainer role of blender-git, and i pushed something perhaps controversial. please see https://aur.archlinux.org/packages/blender-git#comment-906706

> Hello friends,
> 
> I, the old maintainer of this package, Fred Brennan, am back.
> 
> @bartus did a good job here and I don't mind if he keeps pushing but due to the broken state the package was in took it upon myself.
> 
> I want to make y'all aware of a major change.
> 
> Please see https://aur.archlinux.org/cgit/aur.git/commit/?h=blender-git&id=951939b42a00cee9eaf19654d0163703e6476ea1
> 
> This package will now PROMPT you to change your VCSCLIENTS to tell git NOT to pull the whole repo. I'd like to justify this.
> 
> This package is enormous. Many use AUR helpers. The Blender Git server was craawling for me. I've used Arch since age 16, I understand this is not how we do things, and so I have done my very best to make it painless.
> 
> To pull a whole Git repository and never be prompted, supply VCSCLIENTS_IGNORE_BLENDER_GIT_AUR=y in your environment.
> 
> I felt this breaking change was fair as the package was broken for months.
> 
> HOWEVER, I am not deaf to community concerns. If you hate this, tell me, and I will revert the commit. Thanks.
> 

i didn't mean to go over anyone's head. if any recent commiter wants that gone i'll do it until we can discuss it as a group.

@bartoszek @stativ @dexterlb

**Comment by ctrlcctrlv** [comment]
i only pushed that so urgently as i thought i might really bring the server down entirely if i tried to push a normal fix commit. i was getting only around 100KB/s.

**Comment by ctrlcctrlv** [comment]
i conferred with @lazydodo, a Blender core member, on their chat, and we found a solution that isn't so drastic. using the github mirror, which is updated very close to the projects.blender.org, which he confirmed has known issues and is unstable. i am pushing another commit now.

**Comment by dexterlb** [comment]
I think the github mirror solution will work for now.

Maybe we can leave the suggestion to use `--depth 1`, but I think that using `read -p` is a bit too invasive and may break some people's workflows. It could just be a suggestion message instead?

**Comment by ctrlcctrlv** [comment]
hi @dexterlb 

i reverted the change on the AUR. i don't think a suggestion is necessary as i was only doing it because i was worried the AUR helpers of the world would DDoS blender.

people can look into `--depth` flag at their leisure now that we've solved the main problem, the slow upstream dev serverr. :)

**Comment by ctrlcctrlv** [comment]
@bartoszek just sent some messages on the AUR which i relpied to. if he can add me as a maintainer of this repo i'll start pushing my changes here too.

i rely on this package , i just had a period where i wasn't on Arch much due to personal issues but am back for the foreseeable future.

**Comment by bartoszek** [comment]
@ctrlcctrlv I'm all for GitHub mirror of blender, as main server just hangs for minutes when git fetching changes.
About popping prompts during build: I consider those a crime against the humanity 🙄 yaourt evil spawn.
Just use `makepkg key=var` to alter the `PKGBUILD` behavior is much cleaner.

**Comment by ctrlcctrlv** [comment]
We totally agree on that, I never would have left that totally. Gonna close this out as I was able to work it out with the upstream. :-)

AUR is diverging significantly from this repo though so remember to add me here when you get a chance.
