### ISSUE TITLE
Updates cause all files to be rebuild each time?

### ISSUE THREAD

**Issue by danielkrajnik** [bartoszek/AUR-blender-git#21]
On each update blender-git package recompiles every file all over again - it can take over an hour and seems redundant given that manual compilation only rebuilds files that actually changed. Is anyone experiencing a similar issue?

![image](https://github.com/bartoszek/AUR-blender-git/assets/15096799/89ec84bb-812c-48a5-836d-e2c3a0b2b608)

**Comment by bartoszek** [comment]
I'm not intimately familiar with `paru`, but perhaps `ccache` could be of use here.

**Comment by danielkrajnik** [comment]
ccache did speed it up, but it still could take 10-20 minutes. I've eventually gave up and just compiled it directly from git and rebuild on a schedule it via a cron job.

I've never understood why Arch Linux package manager doesn't compile only the changed files and create a completely new package each time. Maybe it would just introduce too many complications. I'm wondering how does it look on gentoo.

**Comment by bartoszek** [comment]
@danielkrajnik will check `paru` + `ccache`
On my setup `aurutil` + `ccache` it works fine: ~100 speedup except `nvcc,ptex` (requires `nvccache` )
[![asciicast](https://asciinema.org/a/DEmWFzwCPfb3nOc2j6Y45ZZih.svg)](https://asciinema.org/a/DEmWFzwCPfb3nOc2j6Y45ZZih)
As for `makepkg` clearing the source tree before building it's a solution for reproducibility issues.
System clear build artifacts from prev run to avoid aberration in the current build. 🚧

**Comment by bartoszek** [comment]
@danielkrajnik Well, that's an aur-helper issue; neither `paru` nor `aurutils` or any helper I'm aware of has this implemented by default. If you simply use `makepkg` and enable `ccache` in `makepkg.conf` it will work as intended, caching compilation results and reusing them during rebuild. You can also do incremental rebuild by calling `makepkg --noprepare` which will reuse current `src` but reliability of such build depends on per package configuration and/or upstream maintainer build spec. For this package it won't work as source requires some patching before build and this has to be redone every time upstream code gets updated.
