### ISSUE TITLE
A failure occurred in prepare

### ISSUE THREAD

**Issue by rhysday** [bartoszek/AUR-blender-git#6]
CONFLICT (content): Merge conflict in source/blender/windowmanager/intern/wm_files_link.c
Auto-merging source/blender/editors/object/object_relations.c
CONFLICT (content): Merge conflict in source/blender/editors/object/object_relations.c
Auto-merging source/blender/editors/object/object_add.c
CONFLICT (content): Merge conflict in source/blender/editors/object/object_add.c
Auto-merging source/blender/blenkernel/intern/scene.c
CONFLICT (content): Merge conflict in source/blender/blenkernel/intern/scene.c
Auto-merging source/blender/blenkernel/intern/object.c
CONFLICT (content): Merge conflict in source/blender/blenkernel/intern/object.c
Auto-merging source/blender/blenkernel/intern/lib_remap.c
CONFLICT (content): Merge conflict in source/blender/blenkernel/intern/lib_remap.c
Auto-merging source/blender/blenkernel/intern/collection.c
CONFLICT (content): Merge conflict in source/blender/blenkernel/intern/collection.c
Auto-merging source/blender/blenkernel/BKE_lib_remap.h
CONFLICT (content): Merge conflict in source/blender/blenkernel/BKE_lib_remap.h
error: could not revert 43bc494892c... IDManagement: Remove deprecated `BKE_libblock_relink_to_newid` usages.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by bartoszek** [comment]
Fixed in 18212a56c325bbe81ef747958fb6a7acc5e23dfc
