### ISSUE TITLE
recent build fails

### ISSUE THREAD

**Issue by Sinasta** [bartoszek/AUR-blender-git#9]
when trying to build there is an error since some days:

Building blender-git...
==> Making package: blender-git 3.2.r112632.g5b3a415a59c-1 (Mi 16 Feb 2022 16:21:06 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating blender git repo...
Fetching origin
  -> Updating blender-addons.git git repo...
Fetching origin
  -> Updating blender-addons-contrib.git git repo...
Fetching origin
  -> Updating blender-translations.git git repo...
Fetching origin
  -> Updating blender-dev-tools.git git repo...
Fetching origin
  -> Found usd_python.patch
  -> Found embree.patch
  -> Found openexr3.patch
==> Validating source files with sha256sums...
    blender ... Skipped
    blender-addons.git ... Skipped
    blender-addons-contrib.git ... Skipped
    blender-translations.git ... Skipped
    blender-dev-tools.git ... Skipped
    usd_python.patch ... Passed
    embree.patch ... Passed
    openexr3.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of blender git repo...
Cloning into 'blender'...
done.
Updating files:  96% (11544/11947)
Updating files:  97% (11589/11947)
Updating files:  98% (11709/11947)
Updating files:  99% (11828/11947)
Updating files: 100% (11947/11947)
Updating files: 100% (11947/11947), done.
Switched to a new branch 'makepkg'
  -> Creating working copy of blender-addons.git git repo...
Cloning into 'blender-addons.git'...
done.
  -> Creating working copy of blender-addons-contrib.git git repo...
Cloning into 'blender-addons-contrib.git'...
done.
  -> Creating working copy of blender-translations.git git repo...
Cloning into 'blender-translations.git'...
done.
  -> Creating working copy of blender-dev-tools.git git repo...
Cloning into 'blender-dev-tools.git'...
done.
==> Starting prepare()...
Submodule 'release/datafiles/locale' (/var/tmp/pamac-build-sinasta/blender-git/blender-translations.git) registered for path 'release/datafiles/locale'
Submodule 'release/scripts/addons' (/var/tmp/pamac-build-sinasta/blender-git/blender-addons.git) registered for path 'release/scripts/addons'
Submodule 'release/scripts/addons_contrib' (/var/tmp/pamac-build-sinasta/blender-git/blender-addons-contrib.git) registered for path 'release/scripts/addons_contrib'
Submodule 'source/tools' (/var/tmp/pamac-build-sinasta/blender-git/blender-dev-tools.git) registered for path 'source/tools'
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/release/datafiles/locale'...
done.
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/release/scripts/addons'...
done.
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/release/scripts/addons_contrib'...
done.
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/source/tools'...
done.
Submodule path 'release/datafiles/locale': checked out 'af8f04db7686d1851d3ac9091472ca21989c8ef3'
Submodule path 'release/scripts/addons': checked out 'f66ad054cff00053dea113698a376acc32ae971f'
Submodule path 'release/scripts/addons_contrib': checked out '61e45814503f51963c91c51aaf764612e7c5dc72'
Submodule path 'source/tools': checked out '3fc56d7bc28f83c864c37503700a8a182f77a59b'
Checking patch build_files/cmake/Modules/FindEmbree.cmake...
error: while searching for:
#  EMBREE_ROOT_DIR, The base directory to search for Embree.
#                        This can also be an environment variable.
#  EMBREEFOUND, If false, do not try to use Embree.

#=============================================================================
# Copyright 2018 Blender Foundation.

error: patch failed: build_files/cmake/Modules/FindEmbree.cmake:7
error: build_files/cmake/Modules/FindEmbree.cmake: patch does not apply
Checking patch intern/cycles/blender/CMakeLists.txt...
Hunk #1 succeeded at 75 (offset 8 lines).
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by Sinasta** [comment]
i am using ccache but i dont think this is the reason.

**Comment by bartoszek** [comment]
Fixed in 13fa02625513a17e2237aa93002f8a7cd2a7236e

**Comment by Sinasta** [comment]
Thank you for the quick fix. i now get this error:

Building blender-git...
==> Making package: blender-git 3.2.r112632.g5b3a415a59c-1 (Fr 18 Feb 2022 11:38:17 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning blender git repo...
Cloning into bare repository '/var/tmp/pamac-build-sinasta/blender-git/blender'...
  -> Cloning blender-addons.git git repo...
Cloning into bare repository '/var/tmp/pamac-build-sinasta/blender-git/blender-addons.git'...
  -> Cloning blender-addons-contrib.git git repo...
Cloning into bare repository '/var/tmp/pamac-build-sinasta/blender-git/blender-addons-contrib.git'...
  -> Cloning blender-translations.git git repo...
Cloning into bare repository '/var/tmp/pamac-build-sinasta/blender-git/blender-translations.git'...
  -> Cloning blender-dev-tools.git git repo...
Cloning into bare repository '/var/tmp/pamac-build-sinasta/blender-git/blender-dev-tools.git'...
  -> Found usd_python.patch
  -> Found embree.patch
  -> Found openexr3.patch
==> Validating source files with sha256sums...
    blender ... Skipped
    blender-addons.git ... Skipped
    blender-addons-contrib.git ... Skipped
    blender-translations.git ... Skipped
    blender-dev-tools.git ... Skipped
    usd_python.patch ... Passed
    embree.patch ... Passed
    openexr3.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of blender git repo...
Cloning into 'blender'...
done.
Switched to a new branch 'makepkg'
  -> Creating working copy of blender-addons.git git repo...
Cloning into 'blender-addons.git'...
done.
  -> Creating working copy of blender-addons-contrib.git git repo...
Cloning into 'blender-addons-contrib.git'...
done.
  -> Creating working copy of blender-translations.git git repo...
Cloning into 'blender-translations.git'...
done.
  -> Creating working copy of blender-dev-tools.git git repo...
Cloning into 'blender-dev-tools.git'...
done.
==> Starting prepare()...
Submodule 'release/datafiles/locale' (/var/tmp/pamac-build-sinasta/blender-git/blender-translations.git) registered for path 'release/datafiles/locale'
Submodule 'release/scripts/addons' (/var/tmp/pamac-build-sinasta/blender-git/blender-addons.git) registered for path 'release/scripts/addons'
Submodule 'release/scripts/addons_contrib' (/var/tmp/pamac-build-sinasta/blender-git/blender-addons-contrib.git) registered for path 'release/scripts/addons_contrib'
Submodule 'source/tools' (/var/tmp/pamac-build-sinasta/blender-git/blender-dev-tools.git) registered for path 'source/tools'
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/release/datafiles/locale'...
done.
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/release/scripts/addons'...
done.
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/release/scripts/addons_contrib'...
done.
Cloning into '/var/tmp/pamac-build-sinasta/blender-git/src/blender/source/tools'...
done.
Submodule path 'release/datafiles/locale': checked out 'af8f04db7686d1851d3ac9091472ca21989c8ef3'
Submodule path 'release/scripts/addons': checked out 'b0274e50da58bc1f0086794a16029ec6e2e9b927'
Submodule path 'release/scripts/addons_contrib': checked out '61e45814503f51963c91c51aaf764612e7c5dc72'
Submodule path 'source/tools': checked out '3fc56d7bc28f83c864c37503700a8a182f77a59b'
Checking patch build_files/cmake/Modules/FindEmbree.cmake...
Checking patch intern/cycles/blender/CMakeLists.txt...
Hunk #1 succeeded at 75 (offset 8 lines).
Applied patch build_files/cmake/Modules/FindEmbree.cmake cleanly.
Applied patch intern/cycles/blender/CMakeLists.txt cleanly.
Checking patch build_files/cmake/platform/platform_unix.cmake...
Hunk #1 succeeded at 331 (offset 11 lines).
Checking patch source/blender/io/usd/CMakeLists.txt...
Hunk #1 succeeded at 35 (offset -13 lines).
Applied patch build_files/cmake/platform/platform_unix.cmake cleanly.
Applied patch source/blender/io/usd/CMakeLists.txt cleanly.
Checking patch build_files/cmake/Modules/FindOpenEXR.cmake...
error: while searching for:
SET(_openexr_libs_ver_init "2.0")

SET(_openexr_FIND_COMPONENTS
  Half
  Iex
  IlmImf
  IlmThread
  Imath
)

SET(_openexr_SEARCH_DIRS

error: patch failed: build_files/cmake/Modules/FindOpenEXR.cmake:34
error: build_files/cmake/Modules/FindOpenEXR.cmake: patch does not apply
Checking patch source/blender/imbuf/intern/openexr/openexr_api.cpp...
error: while searching for:
#include <ImfChannelList.h>
#include <ImfCompression.h>
#include <ImfCompressionAttribute.h>
#include <ImfIO.h>
#include <ImfInputFile.h>
#include <ImfOutputFile.h>
#include <ImfPixelType.h>
#include <ImfStandardAttributes.h>

error: patch failed: source/blender/imbuf/intern/openexr/openexr_api.cpp:38
error: source/blender/imbuf/intern/openexr/openexr_api.cpp: patch does not apply
==> ERROR: A failure occurred in prepare().
    Aborting...
